/* tslint:disable */
/* eslint-disable */
/**
 * ReactMoviesAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Dates
 */
export interface Dates {
  /**
   *
   * @type {string}
   * @memberof Dates
   */
  maximum?: string | null;
  /**
   *
   * @type {string}
   * @memberof Dates
   */
  minimum?: string | null;
}

/**
 * Check if a given object implements the Dates interface.
 */
export function instanceOfDates(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function DatesFromJSON(json: any): Dates {
  return DatesFromJSONTyped(json, false);
}

export function DatesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Dates {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    maximum: !exists(json, "maximum") ? undefined : json["maximum"],
    minimum: !exists(json, "minimum") ? undefined : json["minimum"],
  };
}

export function DatesToJSON(value?: Dates | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    maximum: value.maximum,
    minimum: value.minimum,
  };
}
