/* tslint:disable */
/* eslint-disable */
/**
 * ReactMoviesAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { Dates } from "./Dates";
import { DatesFromJSON, DatesFromJSONTyped, DatesToJSON } from "./Dates";
import type { NewReleaseResult } from "./NewReleaseResult";
import {
  NewReleaseResultFromJSON,
  NewReleaseResultFromJSONTyped,
  NewReleaseResultToJSON,
} from "./NewReleaseResult";

/**
 *
 * @export
 * @interface NewReleaseMovies
 */
export interface NewReleaseMovies {
  /**
   *
   * @type {Dates}
   * @memberof NewReleaseMovies
   */
  dates?: Dates;
  /**
   *
   * @type {number}
   * @memberof NewReleaseMovies
   */
  page?: number;
  /**
   *
   * @type {Array<NewReleaseResult>}
   * @memberof NewReleaseMovies
   */
  results?: Array<NewReleaseResult> | null;
  /**
   *
   * @type {number}
   * @memberof NewReleaseMovies
   */
  totalPages?: number;
  /**
   *
   * @type {number}
   * @memberof NewReleaseMovies
   */
  totalResults?: number;
}

/**
 * Check if a given object implements the NewReleaseMovies interface.
 */
export function instanceOfNewReleaseMovies(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function NewReleaseMoviesFromJSON(json: any): NewReleaseMovies {
  return NewReleaseMoviesFromJSONTyped(json, false);
}

export function NewReleaseMoviesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): NewReleaseMovies {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    dates: !exists(json, "dates") ? undefined : DatesFromJSON(json["dates"]),
    page: !exists(json, "page") ? undefined : json["page"],
    results: !exists(json, "results")
      ? undefined
      : json["results"] === null
        ? null
        : (json["results"] as Array<any>).map(NewReleaseResultFromJSON),
    totalPages: !exists(json, "total_pages") ? undefined : json["total_pages"],
    totalResults: !exists(json, "total_results")
      ? undefined
      : json["total_results"],
  };
}

export function NewReleaseMoviesToJSON(value?: NewReleaseMovies | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    dates: DatesToJSON(value.dates),
    page: value.page,
    results:
      value.results === undefined
        ? undefined
        : value.results === null
          ? null
          : (value.results as Array<any>).map(NewReleaseResultToJSON),
    total_pages: value.totalPages,
    total_results: value.totalResults,
  };
}
