/* tslint:disable */
/* eslint-disable */
/**
 * ReactMoviesAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { TopRatedMovies } from "./TopRatedMovies";
import {
  TopRatedMoviesFromJSON,
  TopRatedMoviesFromJSONTyped,
  TopRatedMoviesToJSON,
} from "./TopRatedMovies";

/**
 *
 * @export
 * @interface TopRatedResult
 */
export interface TopRatedResult {
  /**
   *
   * @type {number}
   * @memberof TopRatedResult
   */
  page?: number;
  /**
   *
   * @type {Array<TopRatedMovies>}
   * @memberof TopRatedResult
   */
  results?: Array<TopRatedMovies> | null;
  /**
   *
   * @type {number}
   * @memberof TopRatedResult
   */
  totalPages?: number;
  /**
   *
   * @type {number}
   * @memberof TopRatedResult
   */
  totalResults?: number;
}

/**
 * Check if a given object implements the TopRatedResult interface.
 */
export function instanceOfTopRatedResult(value: object): boolean {
  let isInstance = true;

  return isInstance;
}

export function TopRatedResultFromJSON(json: any): TopRatedResult {
  return TopRatedResultFromJSONTyped(json, false);
}

export function TopRatedResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TopRatedResult {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    page: !exists(json, "page") ? undefined : json["page"],
    results: !exists(json, "results")
      ? undefined
      : json["results"] === null
        ? null
        : (json["results"] as Array<any>).map(TopRatedMoviesFromJSON),
    totalPages: !exists(json, "total_pages") ? undefined : json["total_pages"],
    totalResults: !exists(json, "total_results")
      ? undefined
      : json["total_results"],
  };
}

export function TopRatedResultToJSON(value?: TopRatedResult | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    page: value.page,
    results:
      value.results === undefined
        ? undefined
        : value.results === null
          ? null
          : (value.results as Array<any>).map(TopRatedMoviesToJSON),
    total_pages: value.totalPages,
    total_results: value.totalResults,
  };
}
