/* tslint:disable */
/* eslint-disable */
/**
 * ReactMoviesAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { TopRatedResult } from "../models/index";
import { TopRatedResultFromJSON, TopRatedResultToJSON } from "../models/index";

export interface ApiMovieTopratedGetRequest {
  page?: number;
}

/**
 *
 */
export class MovieApi extends runtime.BaseAPI {
  /**
   */
  async apiMovieTopratedGetRaw(
    requestParameters: ApiMovieTopratedGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TopRatedResult>> {
    const queryParameters: any = {};

    if (requestParameters.page !== undefined) {
      queryParameters["page"] = requestParameters.page;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/movie/toprated`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      TopRatedResultFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiMovieTopratedGet(
    requestParameters: ApiMovieTopratedGetRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TopRatedResult> {
    const response = await this.apiMovieTopratedGetRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
